name: Auto YouTube Video Post

on:
  schedule:
    - cron: '0 7 * * *'  # Daily at 07:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3-tk
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip list  # Show installed packages for debugging

      - name: Create credentials file
        run: |
          echo "${{ secrets.YOUTUBE_CLIENT_JSON }}" > client_secret.json

      - name: Create .env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

      - name: Run script
        run: |
          python main.py
